version: '3.7'

services:
    api:
        image: api
        command: sh -c "python3 __main__.py"
        build:
            context: ./api
            dockerfile: Dockerfile
        depends_on:
            - tg_bot
        ports:
          - 5000:5000
        restart: always

    tg_bot:
        image: tg_bot
        command: sh -c "python3 __main__.py"
        build:
            context: ./bot
            dockerfile: Dockerfile
        env_file:
            - ./bot/.env
        restart: always
