version: '3.7'

services:
    api:
        image: api
        command: sh -c "python3 __main__.py"
        build:
            context: ./api
            dockerfile: Dockerfile
        depends_on:
            - bot
        ports:
          - 5000:5000
        restart: always

    bot:
        image: bot
        command: sh -c "python3 __main__.py"
        build:
            context: ./bot
            dockerfile: Dockerfile
        environment:
            PYTHONPATH: "/bot/"
        env_file:
            - ./bot/.env
        restart: always
